/**
 * The runsheet: one printable page that states the household's position, what
 * is about to change, what is still unconfirmed, and how to update it.
 *
 * The dashboard is for exploring. This is for agreeing — a document two people
 * can read at the kitchen table and both know they are looking at the same
 * numbers. It is regenerated on every build, so it cannot drift from the
 * dashboard, and it carries its own provenance so nobody has to remember which
 * figures came from a bank and which came from an assumption.
 */

const money = (n, dp = 0) => {
  const v = Math.abs(n).toLocaleString('en-US', {
    minimumFractionDigits: dp, maximumFractionDigits: dp,
  });
  return `${n < 0 ? '−' : ''}$${v}`;
};
const pct = (n, dp = 1) => `${n.toFixed(dp)}%`;
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const longDate = (d) => {
  const [y, m, day] = d.split('-');
  return `${MONTHS[+m - 1]} ${+day}, ${y}`;
};

/** `| a | b |` rows with a header, padded so the raw file reads cleanly too. */
function table(headers, rows, align = []) {
  const all = [headers, ...rows].map((r) => r.map((c) => String(c ?? '')));
  const w = headers.map((_, i) => Math.max(...all.map((r) => r[i].length)));
  const pad = (c, i) => (align[i] === 'r' ? c.padStart(w[i]) : c.padEnd(w[i]));
  const line = (r) => `| ${r.map(pad).join(' | ')} |`;
  const rule = `| ${w.map((n, i) => (align[i] === 'r' ? `${'-'.repeat(n - 1)}:` : '-'.repeat(n))).join(' | ')} |`;
  return [line(all[0]), rule, ...all.slice(1).map(line)].join('\n');
}

export function buildRunsheet(p) {
  const H = p.headline;
  const m = p.mortgage;
  const bd = m.buydown;
  const pay = p.paycheck;
  const tax = pay.tax;
  const re = p.realEstate[0];
  const out = [];
  const w = (s = '') => out.push(s);

  w(`# Household runsheet`);
  w();
  w(`**${p.meta.household.names.join(' and ')}** · ${p.meta.household.residence}`);
  w(`Position as of **${longDate(p.meta.asOf)}**. Generated ${p.meta.generated.slice(0, 10)} `
    + `from ${p.meta.txCount.toLocaleString()} transactions covering `
    + `${longDate(p.meta.firstDate)} to ${longDate(p.meta.lastDate)}.`);
  w();
  w(`> This file is regenerated by \`npm run finance\`. Edit \`config.json\`, not this — `
    + `anything typed here is overwritten on the next build.`);
  w();
  w('---');
  w();

  // ── The question this was built to answer ────────────────────────────────
  const A = p.affordability;
  if (A) {
    const nowS = A.scenarios[0];
    const endS = A.scenarios[A.scenarios.length - 1];
    w('## Can we carry the house?');
    w();
    w(nowS.surplus < 0
      ? `**Not on income alone. The operating gap is about ${money(Math.abs(nowS.surplus))} a `
        + `month, widening to ${money(Math.abs(endS.surplus))} by late 2027.**`
      : `**Yes — about ${money(nowS.surplus)} a month spare on current spending.**`);
    w();
    w(`Housing went from ${money(A.oldHousingMonthly)} a month to ${money(A.housingNow)} and `
      + `nothing else changed. Take-home is ${money(A.takeHome)}, but `
      + `${money(A.withholdingShortfall)} of that is tax owed and not withheld, so the figure to `
      + `plan against is ${money(A.sustainableIncome)}.`);
    w();
    w(table(['', 'Per month'], [
      ['Spendable income', money(A.sustainableIncome)],
      ['Housing', money(-nowS.housing)],
      ['Everything else', money(-A.baseline)],
      ['**Operating gap**', `**${money(nowS.surplus)}**`],
      ['Standing savings transfers', money(-A.savingsNow)],
      ['**Net cash each month**', `**${money(nowS.netCash)}**`],
    ], ['l', 'r']));
    w();
    w(`### Two different kinds of move`);
    w();
    w(`Standing transfers are down from ${money(A.savingsTrailing)}/mo to ${money(A.savingsNow)}/mo `
      + `— Wealthfront cash stopped, the index fund to $100, the 529s from $450 to $150. That is `
      + `**${money(A.savingsReduced)}/mo** of real cash relief and it is why the account drains `
      + `slower. But it does not narrow the operating gap, because that gap was measured before `
      + `any saving. Money not invested is money kept, not money earned.`);
    w();
    w(`Trimming every category that can plausibly move is worth about **${money(A.maxTrim)}/mo**:`);
    w();
    w(table(['Move', 'Worth', 'Running'],
      A.levers.slice(0, 6).map((l) => [l.name, `${money(l.monthly)}/mo`, `${money(l.cumulative)}/mo`]),
      ['l', 'r', 'r']));
    w();
    w(`That leaves **${money(Math.abs(A.afterMaxTrimNow))}/mo** still short today and `
      + `**${money(Math.abs(A.afterMaxTrimLater))}/mo** once both housing increases land. `
      + `Trimming alone does not close it. What does: more income, a lower payment, or accepting `
      + `that the house is funded partly by the proceeds of the last one.`);
    w();
    w(`Nobody is in danger. At the current burn the spendable cash lasts **${A.runwayMonths} `
      + `months**, and with investments behind it, years. The question is not solvency — it is `
      + `whether the windfall is meant to be spent this way.`);
    w();
    w(`Fixed recurring charges that could simply stop, excluding utilities and insurance, run `
      + `**${money(A.cuttableAnnual)} a year** (${money(A.cuttableAnnual / 12)}/mo) across `
      + `${A.cuttable.length} commitments. The Committed monthly page lists every one.`);
    w();
    w('---');
    w();
  }

  // ── Position ──────────────────────────────────────────────────────────────
  w('## Where things stand');
  w();
  w(table(['', 'Amount'], [
    ['**Net worth**', `**${money(H.netWorth)}**`],
    ['Cash and savings', money(H.cashTotal)],
    ['— of which spendable today', money(H.cashAvailable)],
    ['— of which still on hold', money(H.cashOnHold)],
    ['Investments', money(H.investTotal)],
    [`${re.name}, appraised`, money(H.propertyValue)],
    ['Mortgage', money(-H.mortgageBalance)],
    ['Credit cards', money(H.creditTotal)],
    ['**Home equity**', `**${money(H.homeEquity)}**`],
  ], ['l', 'r']));
  w();

  // ── Income ────────────────────────────────────────────────────────────────
  w('## What comes in');
  w();
  w(table(['', 'Per cheque', 'Per year'],
    pay.earners.map((e) => [
      `${e.name} — ${e.title}`, money(e.gross, 2), money(e.annualGross),
    ]).concat([
      ['**Household gross**', `**${money(pay.household.grossPerPeriod, 2)}**`, `**${money(pay.household.annualGross)}**`],
      ['Lands in the bank', money(pay.household.netPerPeriod, 2), money(pay.household.annualNet)],
      ['Employer-paid benefits on top', '', money(pay.household.annualEmployerBenefits)],
      ['**Total compensation**', '', `**${money(pay.household.totalComp)}**`],
    ]), ['l', 'r', 'r']));
  w();
  w(`Saving, counting what payroll takes before the deposit lands: `
    + `**${money(pay.household.trueSavingsAnnual)} a year, ${pct(pay.household.trueSavingsRateOfGross)} of gross.** `
    + `Bank transfers alone show only ${money(H.avgSavings)}/mo of that; the pension, both `
    + `403(b)s, the HSA and the district's match never touch a visible account.`);
  w();
  w(`Pay is not flat. Summer months run light and December carries a third pay period, `
    + `so a budget built on the annual average will be short in July.`);
  w();

  // ── Obligations ───────────────────────────────────────────────────────────
  w('## What goes out');
  w();
  const fixed = p.recurring.filter((r) => r.status === 'active');
  w(table(['', 'Per month', 'Note'], [
    ['Mortgage — principal & interest', money(bd.borrowerPI, 2), `${pct(bd.effectiveRate * 100, 3)} while the buydown runs`],
    ['Mortgage — escrow', money(m.escrow.totalMonthly, 2), 'Property tax and homeowners insurance'],
    ['**Housing, all in**', `**${money(bd.borrowerPI + m.escrow.totalMonthly, 2)}**`, `${pct(H.housingRatio)} of take-home`],
    ['Everything else, average', money(H.avgExpense), 'Trailing 12 months, house transition excluded'],
    ['Recurring commitments', money(fixed.reduce((s, r) => s + r.annual, 0) / 12), `${fixed.length} detected charges`],
  ], ['l', 'r', 'l']));
  w();

  // ── What changes ──────────────────────────────────────────────────────────
  w('## What changes, and when');
  w();
  w(`**Sep 2027 — the buydown expires.** UWM currently pays ${money(bd.monthlySubsidy, 2)} of the `
    + `interest each month, which is why the payment is ${money(bd.borrowerPI, 2)} rather than `
    + `${money(m.monthlyPI, 2)}. It is a fixed-term subsidy worth ${money(bd.subsidyTotal)} in total, `
    + `not a rate. From the ${longDate('2027-09-01')} payment the note rate of ${pct(m.rate * 100, 3)} `
    + `applies in full.`);
  w();
  w(`**At the next reassessment — escrow catches up.** Escrow collects `
    + `${money(p.house.taxCheck.escrowTaxAnnual)} a year for property tax, which is the 2025 `
    + `assessment on this house before it sold and before the renovation. A ${money(re.purchasePrice)} `
    + `purchase in Maricopa County is more likely billed near ${money(p.house.taxCheck.likelyTaxAnnual)}. `
    + `Expect a shortage notice and roughly ${money(p.house.taxCheck.escrowGap)}/mo more.`);
  w();
  w(`**Together: about ${money(bd.monthlySubsidy + p.house.taxCheck.escrowGap)}/mo more by late 2027**, `
    + `taking housing from ${money(bd.borrowerPI + m.escrow.totalMonthly)} to roughly `
    + `${money(m.monthlyPI + m.escrow.totalMonthly + p.house.taxCheck.escrowGap)}. Neither is a surprise `
    + `and neither is negotiable, so the useful move is to start setting the difference aside now.`);
  w();
  if (tax) {
    w(`**April ${tax.assumptions.year + 1} — tax.** Withholding looks about `
      + `${money(Math.abs(tax.totalGap))} ${tax.totalGap > 0 ? 'short' : 'ahead'}. `
      + `One of the two paycheques withholds no federal tax at all, so household federal `
      + `withholding is ${money(tax.federalWithheld)} a year against roughly `
      + `${money(tax.federalOnWages)} of projected tax on wages, plus the gain on the July `
      + `Wealthfront sale. This is arithmetic over stated assumptions, not tax advice — the `
      + `working is on the dashboard's Paycheck page.`);
    w();
  }

  // ── Open items ────────────────────────────────────────────────────────────
  w('## Open items');
  w();
  const items = [];
  for (const d of p.dataQuality.filter((x) => x.severity !== 'good')) {
    items.push([d.severity === 'serious' ? 'Worth fixing' : 'Heads up', d.title]);
  }
  if (items.length) w(table(['', 'Item'], items));
  else w('_Nothing outstanding._');
  w();

  // ── Procedure ─────────────────────────────────────────────────────────────
  w('## How to update this');
  w();
  w('```bash');
  w('npm run finance:import -- ~/Downloads/"Simplifi - Transactions.csv"');
  w('npm run finance                 # rebuild, re-encrypt, regenerate this file');
  w('git add public/finances/data.enc.json && git commit -m "Update finance data" && git push');
  w('```');
  w();
  w('Importing is safe to repeat. The same export merged twice changes nothing, a longer '
    + 'export adds only what is new, and a correction recorded against a transaction id '
    + 'survives every future import.');
  w();
  w('**Things that only change by hand, in `finance-private/config.json`:**');
  w();
  w(table(['What', 'Where', 'Why'], [
    ['Account balances', '`accounts[].balance`', 'Simplifi carries them; check after big moves'],
    ['Barclays', '`manualUpdate` + `manualTransactions`', 'No feed — they stopped sharing with budgeting apps'],
    ['Paycheck detail', '`income.earners`', 'From the direct-deposit receipts'],
    ['Tax assumptions', '`taxAssumptions`', 'Children, brackets, cost basis'],
    ['House projects', '`houseProjects.items`', 'Quotes, decisions, what is done'],
    ['Budgets', '`budgets`', 'Monthly targets'],
  ]));
  w();

  // ── Provenance ────────────────────────────────────────────────────────────
  w('## Where the numbers come from');
  w();
  w(table(['Source', 'Covers', 'Used for'], [
    ['Mint export', `${p.meta.firstDate} → ${p.meta.sources.seam}`, 'Spending, income, categories'],
    ['Simplifi export', `after ${p.meta.sources.seam}`, 'Everything, plus balance reconstruction'],
    ['Closing Disclosure', 'Jul 2026', 'Mortgage, buydown, escrow — exact'],
    ['Direct-deposit receipts', 'Aug 2026', 'Gross, deductions, employer contributions — exact'],
    ['Bank pages, typed in', p.meta.asOf, 'Barclays balance and recent activity'],
    ['`config.json`', 'current', 'Balances, assumptions, projects'],
  ]));
  w();
  if (p.meta.ledgerStats) {
    const ls = p.meta.ledgerStats;
    w(`The two exports overlap from Jan 2020 to ${p.meta.sources.seam}, but Simplifi's rows over `
      + `that window are a partial backfill running short of Mint's month by month, so each source `
      + `owns the period it was actually the live system. Mint also recorded many transactions `
      + `twice, once per bank feed and worded differently each time — most visibly every Agua Fria `
      + `paycheque. **${ls.duplicatesSuppressed.toLocaleString()} duplicate rows** are collapsed at `
      + `import; left in, they inflated reported income by roughly $390,000 across the Mint years.`);
    w();
  }
  w(`Balance history is reconstructed by rolling today's figures backward through the ledger, `
    + `which needs both legs of every transfer recorded. Simplifi does that; Mint recorded a card `
    + `payment once. So **net worth and balances are charted from ${p.meta.trustedFrom}**, while `
    + `spending, income and categories use all ${p.meta.months.length} months.`);
  w();
  w('---');
  w();
  w(`_Dashboard: ${'https://lukeallpress.github.io/finances/'} — passphrase-gated. `
    + `Everything in this file is private; \`finance-private/\` is gitignored._`);
  w();

  return out.join('\n');
}
